### ISSUE TITLE
Upload command removes local repository directory

### ISSUE THREAD

**Issue by JoshuaMathias** [scottclowe/python-template-repo#96]
Look closely at the path here at line 121 of https://github.com/scottclowe/python-template-repo/blob/master/setup.py: `here = os.path.abspath(os.path.dirname(__file__))`

When I ran `python setup.py upload`, the repository was completely deleted locally, so all local git cache was removed, etc. Luckily I had pushed all my code! Surely this line is too dangerous to keep this way? 
The next line is `rmtree(here, "dist")`
The path is the first argument, so this doesn't make sense. It looks like it should be `rmtree(os.path.join(here, "dist"))`

Also, it should be meta['version'], not `meta['__version__']`. It looks like this code was never tested.

**Comment by JoshuaMathias** [comment]
I tested that `python setup.py upload` works successfully after the above 2 fixes.

**Comment by scottclowe** [comment]
Hi @JoshuaMathias, thanks for reporting this serious bug! The code for UploadCommand was taken from the setup.py template here https://github.com/kennethreitz/setup.py, but I must have accidentally broken it at some point without realising. I don't use this command myself as part of my own release routine, so I did not notice the bug after it had been introduced.
